version: "3"
services:
  reverseproxy:
    build:
      context: ../../reverse-proxy
    image: kjkrol/udagram:reverseproxy
  udagram-user-api:
    build:
      context: ../../udagram-user-api
    image: kjkrol/udagram:udagram-user-api
  udagram-feed-api:
    build:
      context: ../../udagram-feed-api
    image: kjkrol/udagram:udagram-feed-api
  udagram-frontend:
    build:
      context: ../../udagram-frontend
    image: kjkrol/udagram:udagram-frontend